apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-despachos
spec:
  replicas: 1
  progressDeadlineSeconds: 120
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: backend-despachos
  template:
    metadata:
      labels:
        app: backend-despachos
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: backend-despachos
          image: innovatech-spa-backend:despacho-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=60.0"
            - name: DB_HOST
              value: mysql
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/innovatech-spa
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
